apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mnist-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mnist-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30

# k8s/hpa.yaml (autoscaling) 30% CPU
# this file defines a Horizontal Pod Autoscaler for the MNIST deployment.
# It scales the number of replicas between 1 and 3 based on CPU utilization.
