apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-load-generator-job
spec:
  template:
    spec:
      containers:
        - name: mnist-loader
          image: ml-mnist-kubernetes-mnist-tester:latest
          imagePullPolicy: Never
          command: ["sh", "-c"]
          args:
            - |
              pip install requests pillow &&
              for i in $(seq 1 2000); do
                curl -X POST http://mnist-service:8000/predict -F file=@assets/test_images/mnist_03.png & sleep 0.1
              done &&
              wait
      restartPolicy: Never

# This job will generate load by sending 200 requests to the MNIST service.
# It uses a Python container to install necessary libraries and send requests.
