apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-load-generator-thread-job
spec:
  template:
    spec:
      containers:
        - name: mnist-loader-thread
          image: ml-mnist-kubernetes-tester:latest
          imagePullPolicy: Never
          command: ["sh", "-c"]
          args:
            - |
              pip install requests &&
              python3 assets/load.py
      restartPolicy: Never
